sbatch ./scripts/job_5.script
sbatch ./scripts/job_8.script
sbatch ./scripts/job_11.script
sbatch ./scripts/job_14.script
sbatch ./scripts/job_17.script
sbatch ./scripts/job_20.script
sbatch ./scripts/job_21.script
sbatch ./scripts/job_22.script
sbatch ./scripts/job_23.script
sbatch ./scripts/job_24.script
sbatch ./scripts/job_25.script
sbatch ./scripts/job_26.script
sbatch ./scripts/job_27.script